// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import av "github.com/daneshvar/joy4/av"
import mock "github.com/stretchr/testify/mock"

// AudioDecoder is an autogenerated mock type for the AudioDecoder type
type AudioDecoder struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *AudioDecoder) Close() {
	_m.Called()
}

// Decode provides a mock function with given fields: _a0
func (_m *AudioDecoder) Decode(_a0 []byte) (bool, av.AudioFrame, error) {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func([]byte) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 av.AudioFrame
	if rf, ok := ret.Get(1).(func([]byte) av.AudioFrame); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(av.AudioFrame)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func([]byte) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
