// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import av "github.com/daneshvar/joy4/av"
import mock "github.com/stretchr/testify/mock"

// Demuxer is an autogenerated mock type for the Demuxer type
type Demuxer struct {
	mock.Mock
}

// ReadPacket provides a mock function with given fields:
func (_m *Demuxer) ReadPacket() (av.Packet, error) {
	ret := _m.Called()

	var r0 av.Packet
	if rf, ok := ret.Get(0).(func() av.Packet); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(av.Packet)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Streams provides a mock function with given fields:
func (_m *Demuxer) Streams() ([]av.CodecData, error) {
	ret := _m.Called()

	var r0 []av.CodecData
	if rf, ok := ret.Get(0).(func() []av.CodecData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]av.CodecData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
