// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import av "github.com/daneshvar/joy4/av"
import mock "github.com/stretchr/testify/mock"

// Filter is an autogenerated mock type for the Filter type
type Filter struct {
	mock.Mock
}

// ModifyPacket provides a mock function with given fields: pkt, streams, videoidx, audioidx
func (_m *Filter) ModifyPacket(pkt *av.Packet, streams []av.CodecData, videoidx int, audioidx int) (bool, error) {
	ret := _m.Called(pkt, streams, videoidx, audioidx)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*av.Packet, []av.CodecData, int, int) bool); ok {
		r0 = rf(pkt, streams, videoidx, audioidx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*av.Packet, []av.CodecData, int, int) error); ok {
		r1 = rf(pkt, streams, videoidx, audioidx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
