// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import av "github.com/daneshvar/joy4/av"
import mock "github.com/stretchr/testify/mock"

// Muxer is an autogenerated mock type for the Muxer type
type Muxer struct {
	mock.Mock
}

// WriteHeader provides a mock function with given fields: _a0
func (_m *Muxer) WriteHeader(_a0 []av.CodecData) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]av.CodecData) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WritePacket provides a mock function with given fields: _a0
func (_m *Muxer) WritePacket(_a0 av.Packet) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(av.Packet) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteTrailer provides a mock function with given fields:
func (_m *Muxer) WriteTrailer() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
